name: build

on:
  pull_request: {}
  workflow_dispatch: {}

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 19

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew build :runtime:dokkaHtml

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew :tests:connectedCheck

      - name: Deploy docs to website
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'cashapp/paraphrase' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: runtime/build/dokka/html
          TARGET_FOLDER: docs/latest/
          CLEAN: true
